###
POST localhost:8080/cards
Content-Type: application/json

{
  "nome": "Itau Black",
  "bandeira": "MASTERCARD",
  "renda": 5000,
  "limiteBasico": "5000"
}
###

###
POST localhost:8080/cards
Content-Type: application/json

{
  "nome": "Nubank Gold",
  "bandeira": "MASTERCARD",
  "renda": 2500,
  "limiteBasico": "3000"
}
###

###
POST localhost:8080/cards
Content-Type: application/json

{
  "nome": "Bradesco Elo Grafite",
  "bandeira": "ELO",
  "renda": 4000,
  "limiteBasico": "6000"
}
###

###
GET localhost:8080/cards?renda=2500

###

###
GET localhost:8080/cards?cpf=1234567898
###
