### GET request to example server
POST http://localhost:8080/clients
Content-Type: application/json

{
  "nome": "David Pacifico",
  "cpf": "1234567898",
  "idade": 25
}

###
###
GET http://localhost:8080/clients?cpf=1234567898
###

###
GET http://localhost:8080/clients
###